In [11]:
import numpy as np
import math
from qiskit.quantum_info import Pauli, Operator
from qiskit.quantum_info import SparsePauliOp

from BoseHubbardHamiltonian_class import BoseHubbardHamiltonian

import rustworkx as rx
from qiskit_nature.second_q.hamiltonians.lattices import (
    BoundaryCondition,
    HyperCubicLattice,
    Lattice,
    LatticeDrawStyle,
    LineLattice,
    SquareLattice,
    TriangularLattice,
)


In [2]:
SWAP = np.zeros((4,4),dtype=float)  

In [3]:
SWAP[0][0] = 1
SWAP[1][2] = 1
SWAP[2][1] = 1
SWAP[3][3] = 1

In [4]:
print(SWAP)

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [5]:
SWAPOp = Operator(SWAP)
swap = SparsePauliOp.from_operator(SWAPOp)

In [6]:
print(swap)

SparsePauliOp(['II', 'XX', 'YY', 'ZZ'],
              coeffs=[0.5+0.j, 0.5+0.j, 0.5+0.j, 0.5+0.j])


In [8]:
Swap_AE = SparsePauliOp(['IIIIII', 'XIIIXI', 'YIIIYI', 'ZIIIZI'], [0.5+0.j, 0.5+0.j, 0.5+0.j, 0.5+0.j] )
Swap_BF = SparsePauliOp(['IIIIII', 'IXIIIX', 'IYIIIY', 'IZIIIZ'], [0.5+0.j, 0.5+0.j, 0.5+0.j, 0.5+0.j] )

In [9]:
Swap = Swap_AE.compose(Swap_BF)

In [10]:
print(Swap)

SparsePauliOp(['IIIIII', 'IXIIIX', 'IYIIIY', 'IZIIIZ', 'XIIIXI', 'XXIIXX', 'XYIIXY', 'XZIIXZ', 'YIIIYI', 'YXIIYX', 'YYIIYY', 'YZIIYZ', 'ZIIIZI', 'ZXIIZX', 'ZYIIZY', 'ZZIIZZ'],
              coeffs=[0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j,
 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j,
 0.25+0.j, 0.25+0.j])


In [13]:
#line lattice 
num_nodes = 3 #number of sites in the lattice 
boundary_condition = BoundaryCondition.OPEN #open lattice
line_lattice = LineLattice(num_nodes=num_nodes, boundary_condition=boundary_condition)

In [14]:
num_qubits = 2
num_nodes = 3
H_instance = BoseHubbardHamiltonian(num_nodes, num_qubits, line_lattice)

energy_values =[0.8,1.]
energy_param_ratio = energy_values[0]/energy_values[1]

H_q = H_instance.get_H(energy_values[0],energy_values[1])

In [16]:
H_q.compose(Swap)-Swap.compose(H_q)

SparsePauliOp(['IXIXII', 'IIIXIX', 'IZIXIY', 'IYIXIZ', 'XXIXXI', 'XIIXXX', 'XZIXXY', 'XYIXXZ', 'YXIXYI', 'YIIXYX', 'YZIXYY', 'YYIXYZ', 'ZXIXZI', 'ZIIXZX', 'ZZIXZY', 'ZYIXZZ', 'IXXXII', 'IIXXIX', 'IZXXIY', 'IYXXIZ', 'XXXXXI', 'XIXXXX', 'XZXXXY', 'XYXXXZ', 'YXXXYI', 'YIXXYX', 'YZXXYY', 'YYXXYZ', 'ZXXXZI', 'ZIXXZX', 'ZZXXZY', 'ZYXXZZ', 'IXYYII', 'IIYYIX', 'IZYYIY', 'IYYYIZ', 'XXYYXI', 'XIYYXX', 'XZYYXY', 'XYYYXZ', 'YXYYYI', 'YIYYYX', 'YZYYYY', 'YYYYYZ', 'ZXYYZI', 'ZIYYZX', 'ZZYYZY', 'ZYYYZZ', 'IXZXII', 'IIZXIX', 'IZZXIY', 'IYZXIZ', 'XXZXXI', 'XIZXXX', 'XZZXXY', 'XYZXXZ', 'YXZXYI', 'YIZXYX', 'YZZXYY', 'YYZXYZ', 'ZXZXZI', 'ZIZXZX', 'ZZZXZY', 'ZYZXZZ', 'IYIYII', 'IZIYIX', 'IIIYIY', 'IXIYIZ', 'XYIYXI', 'XZIYXX', 'XIIYXY', 'XXIYXZ', 'YYIYYI', 'YZIYYX', 'YIIYYY', 'YXIYYZ', 'ZYIYZI', 'ZZIYZX', 'ZIIYZY', 'ZXIYZZ', 'IYXYII', 'IZXYIX', 'IIXYIY', 'IXXYIZ', 'XYXYXI', 'XZXYXX', 'XIXYXY', 'XXXYXZ', 'YYXYYI', 'YZXYYX', 'YIXYYY', 'YXXYYZ', 'ZYXYZI', 'ZZXYZX', 'ZIXYZY', 'ZXXYZZ', 'IYYXII', 'IZYXIX', 'IIYX